#FROM ai-base:latest as stage1
FROM dustynv/nano_llm:r36.3.0 as stage1

ENV CUDA_HOME=/usr/local/cuda

ENV BLINKA_FORCECHIP=T234
ENV BLINKA_FORCEBOARD=JETSON_ORIN_NANO
ENV JETSON_MODEL_NAME=JETSON_ORIN_NANO

WORKDIR /


COPY ./scripts/entrypoint.sh /
COPY ./scripts/felix.sh /
COPY ./scripts/train.sh /

RUN apt-get update && apt-get -y install vim i2c-tools libzmq3-dev libzmq5 pkg-config\
   && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip
RUN pip3 install --no-cache-dir --verbose --index-url https://pypi.org/simple \
  pyserial \
  streamlit \
  streamlit-joystick \
  flask \
  flask_cors \
  pandas \
  asyncio-atexit \
  adafruit-blinka \
  adafruit-circuitpython-vl53l0x \
  jetson.GPIO \
  pyzmq \
  click \
  



FROM stage1 as stage2

#COPY ./config/nginx.conf /etc/nginx/sites-enabled/default

#RUN echo "INSTALL NANO-CONTROL"
#RUN git clone https://github.com/kevywilly/nano-control -b felix
#RUN ln -s /nano-control/build /var/www/build

RUN echo "source /entrypoint.sh" >> /root/.bashrc


# DOCKER_BUILDKIT=1 docker build -f Dockerfile -t felix:latest .
# https://www.ros.org/reps/rep-2001.html#id25
